server:
  port: 18091
spring:
  application:
    name: mysql-example
  datasource:
    url: jdbc:mysql://39.106.10.196:3306/javadevmap?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: mypass
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.javadevmap.mysqlexample.model
  mapper-locations: classpath*:mybatis/*/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

