server:
  port: 18040
  
spring:
  application:
    name: zuul

eureka: 
  instance:
    hostname: zuul
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    metadata-map: 
      cluster: main
  client: 
#    service-url: 
#      defaultZone: http://eureka-serverA:18001/eureka/,http://eureka-serverB:18002/eureka/
    region: javadevmap
    availability-zones: 
      javadevmap: map_eureka
    service-url: 
      map_eureka: http://172.17.238.237:18001/eureka/,http://172.17.238.239:18001/eureka/
      
zuul: 
  prefix: /springcloud
  strip-prefix: true
#  ignored-services: SERVICE-PROVIDER
  routes: 
    consumer: 
      path: /consumer/**
      strip-prefix: false
      service-id: SERVICE-CONSUMER
    provider:
      path: /user/**
      strip-prefix: false
      service-id: SERVICE-PROVIDER    

info:
  author: hw
  book: javadevmap
  project: service zuul demo
endpoints: 
  shutdown:
    enabled: true
    sensitive: false

#zuul:
#  routes:
#    consumer:
#      path: /consumer/**
#      strip-prefix: false
#      url: http://localhost:18020/