server:
  port: 18030
spring:
  application:
    name: turbine
  rabbitmq:
    host: 172.17.238.238
    port: 5673
    username: guest
    password: guest
    
eureka:
  instance:
    hostname: turbine
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client: 
#    service-url: 
#      defaultZone: http://eureka-serverA:18001/eureka/,http://eureka-serverB:18002/eureka/
    region: javadevmap
    availability-zones: 
      javadevmap: map_eureka
    service-url: 
      map_eureka: http://172.17.238.237:18001/eureka/,http://172.17.238.239:18001/eureka/

turbine:
  app-config: SERVICE-CONSUMER,SERVICE-PROVIDER,ZUUL
  aggregator: 
    clusterConfig: main
  clusterNameExpression: metadata['cluster']
  combine-host-port: true
info:
  author: hw
  book: javadevmap
  project: turbine demo
endpoints: 
  shutdown:
    enabled: true
    sensitive: false