server:
  port: 18020
spring:
  application:
    name: service-consumer
  rabbitmq:
    host: 172.17.238.238
    port: 5673
    username: guest
    password: guest
  
#  zipkin:
##    locator:
##      discovery:
##        enabled: true
#    enabled: true
#    sender:
#      type: rabbit
#    base-url: http://172.17.238.237:18060
  sleuth:
    stream:
      enabled: true
    enabled: true
    rxjava: 
      schedulers:
        hook:
          enabled: false
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: service-consumer
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map: 
      cluster: main
  client: 
#    service-url: 
#      defaultZone: http://eureka-serverA:18001/eureka/,http://eureka-serverB:18002/eureka/
    region: javadevmap
    availability-zones: 
      javadevmap: map_eureka
    service-url: 
      map_eureka: http://172.17.238.237:18001/eureka/,http://172.17.238.239:18001/eureka/
info:
  author: hw
  book: javadevmap
  project: service consumer demo
endpoints: 
  shutdown:
    enabled: true
    sensitive: false
  refresh:
    enabled: true
    sensitive: false
    
feign:
  hystrix: 
    enabled: true
    
hystrix:    
  threadpool:  
    default:  
      coreSize: 100
  command: 
    default: 
      execution: 
        isolation: 
          thread:
            timeoutInMilliseconds: 2000
#      circuitBreaker:
#        requestVolumeThreshold: 1

custom: 
  foo: application config version 1

            
#hystrix: 
#  command: 
#    default: 
#      execution: 
#        isolation:
#          strategy: SEMAPHORE
#          semaphore:  
#            maxConcurrentRequests: 2000
#          thread:
#            timeoutInMilliseconds: 2000
      
    